### PR TITLE
ERT support for up to 301 bp reads

### PR DESCRIPTION
**Pull request by arun-sub**
Extends #117 to support up to 301 bp reads.

### CODE REVIEW

**Comment by keiranmraine** [comment]
Sorry to pollute this thread.  Can we get some additional documentation about this.  From what I understand:

* This is an optional additional index
* It has an additional memory overhead, so better suited to large input data sets
* Extra command line option when executing to activate

Will this error if reads exceed the 301 b.p. limit?

**Comment by yuk12** [comment]
This codebase implements the idea of accelerating the seeding stage of BWA-MEM2 using enumerated radix trees; thanks to the hard work by @arun-sub.  Initial evaluation shows that it is 10%-40% faster than vanilla bwa-mem2. It consumes relatively more memory, ~70 GB. New command-line options are added to switch to this implementation on the top of vanilla bwa-mem2. Right now it supports read lengths till 301 bp, beyond that it will fail. @keiranmraine do you have use cases for longer short reads?

**Comment by keiranmraine** [comment]
@yuk12 at present we do not have uses for longer than 301bp, I just wanted to be sure that the code will give an non-zero exit code an appropriate error message should longer reads be used.

**Comment by yuk12** [comment]
Ok. Yes, it will report, along with non-zero exit,  if longer reads are used.

**Pull request merged**
